language: php

php:
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.5
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_install:
  - yes '' | pecl -q install -f mongo
  - php --ri mongo

install:
  - composer update $COMPOSER_FLAGS
